### ISSUE TITLE
Set time, timezone

### ISSUE THREAD

**Issue by ChuckLutz** [nerves-project/nerves_networking#8]
- "TODO" item from the Elixir Slack #nerves channel
  - Discussed 23 Feb by ssachse, jschneck, gregmefford
- Need an RTC?
  - NTP? Network up at VM start
  - Expected application workflow
    - Network Start
    - Absolve System Time (expect to block here)
    - App Start
- Roll into nerves.io.ethernet

**Comment by CaptChrisD** [comment]
Do we really feel that the ethernet module should have a time component? 

I agree that a time module would be great to add to the nerves project but seems like it should be it's own module.

**Comment by ChuckLutz** [comment]
The above are my notes from the discussion on #nerves a few weeks ago. I've been mining the channel for communal "TODO" items that come up. Greg suggested I use the Issues in the individual repos to capture them, which I thought was a natural idea. I don't recall who mentioned the idea of rolling it into nerves.io.ethernet, but that comment is why I put it here. Good question, though.

**Comment by CaptChrisD** [comment]
I very much appreciate the effort of moving TODO items into issues! This makes it much easier to track and discuss.

In this case I am not sure about wrapping time into Ethernet is the right thing. Will be curious to hear others opinions on this matter

**Comment by ghitchens** [comment]
Agreed with @ChuckLutz  that NTP support is important and useful, but also agree with @CaptChrisD that this should happen in a module other than this.   I think the work here is to make sure events/callbacks and documentation support the scenario above (callback on internet connectivity being fully available) so that the NTP scenario described can be implemented.    I think example code should also describe how to do this.  I'm leaving this open until those pieces are in place.

**Comment by ChuckLutz** [comment]
Hi gents - thanks for the discussion! As I am still quite the nerves noob, I have no opinion yet as to where the functionality would go; I just wanted to get the to-do recorded somewhere. My description above is just paraphrasing/summary of what others (participants listed) were discussing in #nerves at the time on the subject. Sounds very neat though. As I learn more perhaps I can help; I'm very enthusiastic, but at this point I'm trying to help in "non-code" ways until I get up to speed. I've been solely in a corporate C++/clearcase world for the past decade; I just got a GitHub account, so forgive me if I'm fumbling the procedures at first...

**Comment by CaptChrisD** [comment]
@ChuckLutz I very much appreciate the effort. Placing this issue here is very helpful. Please continue your involvement

**Comment by optikfluffel** [comment]
Is there a workaround to set the current date/time manually?

**Comment by fhunleth** [comment]
I enabled the `date` and `ntpd` commands in all of the default Nerves configurations. This is in nerves-system-br v0.4.0-rc3. I don't think this release has made its way to `bake` yet.

**Comment by GregMefford** [comment]
This can now be easily handled by adding [nerves_ntp](https://github.com/evokly/nerves_ntp) to your project.

**Comment by benrom** [comment]
I use `nerves_ntp` in a project, and when connecting via wifi, as it takes some time to connect to it, the NTP requests are done before the network is up and they fail.
Any way to start ntp automatically right AFTER the connection is up ?

I've managed to start it manually from the console with:
```
Nerves.Ntp.Worker.start_link()
```
